git add GitAddEuler.bat;
git add Euler.sln;
git add Euler.suo;
git add Euler/Euler.csproj;
git add Euler/Program.cs;
git add Euler/EulerProblemEngine.cs;
git add Euler/Problem.cs;
git add Euler/RunResponse.cs;
git add Euler/Problems;
git add Euler/DataStructures;
git status;
